# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-29 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regtime', models.DateTimeField(auto_now_add=True)),
                ('pname', models.CharField(max_length=100)),
                ('pdesc', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('image', models.ImageField(default='', upload_to='webpage/image')),
                ('no', models.IntegerField()),
            ],
        ),
    ]
