# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-29 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('regtime', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200, primary_key=True, serialize=False)),
                ('passw', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('pincode', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('dob', models.CharField(max_length=20)),
            ],
        ),
    ]
