# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-29 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190529_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='no',
            new_name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
