# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-29 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20190529_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
