# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-31 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20190531_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=' ', upload_to='image'),
        ),
    ]
